//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTP.AddToCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentReg
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PrimaryAddress { get; set; }
        public string CityStateZip { get; set; }
        public string PrimaryEmailAddress { get; set; }
        public string PhoneNumber { get; set; }
    }
}
