//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTP.AddToCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cart
    {
        public int cid { get; set; }
        public string Cart_id { get; set; }
        public Nullable<int> fk_Product { get; set; }
        public Nullable<int> qty { get; set; }
    }
}
