//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTP.AddToCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int id { get; set; }
        public string PName { get; set; }
        public string fk_cat { get; set; }
        public string Price { get; set; }
        public string PImage { get; set; }
    }
}
