//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssociateManagement.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRecord
    {
        public int EmployeeID { get; set; }
        public string FullName { get; set; }
        public string Position { get; set; }
        public string OfficeLocation { get; set; }
        public string Age { get; set; }
        public string Salary { get; set; }
    }
}
