--Get the first and last day of a given month
SELECT DATEADD(DD,-(DAY(GETDATE() -1)), GETDATE()) AS FirstDate
SELECT DATEADD(DD,-(DAY(GETDATE())), DATEADD(MM, 1, GETDATE())) AS LastDate

SELECT DATENAME(WEEKDAY, DATEADD(DD, -(DAY(GETDATE() -1)), GETDATE())) AS [First Day]
SELECT DATENAME(WEEKDAY, DATEADD(DD, -(DAY(GETDATE())), DATEADD(MM, 1, GETDATE()))) AS [Last Day]

DECLARE @myDate DATETIME = '10/21/2022';
SELECT DATENAME(WEEKDAY, @myDate)

--Get today's Date name ie. Monday, Tuesday
SELECT DATENAME(W, GETDATE())
SELECT DATENAME(WEEKDAY, GETDATE())

--Get today's Date name ie. January, October
SELECT DATENAME(M, GETDATE())
SELECT DATENAME(MONTH, GETDATE())