//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTP.Main.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_EmpData
    {
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Department { get; set; }
        public string PositionType { get; set; }
        public decimal Salary { get; set; }
        public int CityId { get; set; }
    }
}
