//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTP.Main.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoySecHR_Employee
    {
        public int EmployeeID { get; set; }
        public string FullName { get; set; }
        public string Position { get; set; }
        public string OfficeLocation { get; set; }
        public int Salary { get; set; }
        public string ImagePath { get; set; }
    }
}
